# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2548015b6a65fee8c66c4b58ee33f1d520d1478a0901e72de3bc687bd656a758cd2e1f5ebd5ecc6b0c9b7c6dec8ab44a2e67d0ee5398101de46e1db7f4fe71ff

test:
  secret_key_base: 3b40014a388ffc4330b03fd073a28bbd1f1a6a10394bb2904361be36e8a4dd8b7f435f6b853fc672de50b79d92273eeb20f8e890f985ae2cca0c315f0f8013ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
